"""Gerber (RS-274X) and Excellon drill file export.

File naming/layer set follows LionCircuits' current fab intake standard,
per the "GD001-Glyph-C3 ... gerber_X2_LC" sample package (this supersedes
the earlier "jini_2_double_sde" sample this exporter originally matched):

  TOP.GTL, BOTTOM.GBL, TOPMASK.GTS, BOTTOMMASK.GBS, TOPSILK.GTO,
  BOTTOMSILK.GBO, TOPPASTE.GTP, OUTLINE.GKO
  DRILL.DRL (plated holes), NPTH.DRL (non-plated holes), SLOT.DRL
  (milled slots), DRLMAP.GBR + DRLDRAW.GBR (drill legend/map)

No bottom paste, no Gerber_BoardOut.gbr duplicate this time (both of
those were specific to the older sample).

Note: KiCad's PLOT_CONTROLLER always emits current-spec RS-274X (its own
%FSLAX...% precision, modern D-code selection, G04 comment lines). The
sample package was generated by older CAM tooling (CAM350) using legacy
conventions (G54-prefixed aperture selects, no G04 comments, per-tool
feed/speed parameters in the drill header) that pcbnew doesn't expose a
way to reproduce byte-for-byte. That's a cosmetic difference only — the
RS-274X/Excellon we emit is fully valid and reads correctly in any
CAM/fab tooling — so we match naming, layer selection, and units/format
exactly, without attempting the old aperture-select syntax itself.

Every non-essential sub-step (drill map, slot-file splitting) is wrapped
so it degrades quietly instead of failing the whole export if a given
KiCad version's API doesn't support it — see _safe_step().
"""

import os
import re
import shutil
import time

import pcbnew


def _layer_plan(board):
    """[(layer_id, target_filename), ...] in the fab's required naming.

    Outer layers, both masks, both silks, top paste, and the outline use
    the fixed names from the sample. Any inner copper layers (4+ layer
    boards, not covered by the sample) get a best-effort INNERn.G(n+1)
    name — adjust if your fab expects something else for those.
    """
    plan = [(pcbnew.F_Cu, "TOP.GTL")]

    n = board.GetCopperLayerCount()
    for i in range(1, n - 1):
        layer_id = pcbnew.In1_Cu + (i - 1)
        plan.append((layer_id, "INNER{0}.G{1}".format(i, i + 1)))

    if n > 1:
        plan.append((pcbnew.B_Cu, "BOTTOM.GBL"))

    plan += [
        (pcbnew.F_Mask, "TOPMASK.GTS"),
        (pcbnew.B_Mask, "BOTTOMMASK.GBS"),
        (pcbnew.F_SilkS, "TOPSILK.GTO"),
        (pcbnew.B_SilkS, "BOTTOMSILK.GBO"),
        (pcbnew.F_Paste, "TOPPASTE.GTP"),
        (pcbnew.Edge_Cuts, "OUTLINE.GKO"),
    ]
    return plan


def _rename_to(src_path, out_dir, target_name):
    dst = os.path.join(out_dir, target_name)
    if os.path.abspath(src_path) == os.path.abspath(dst):
        return dst
    if os.path.isfile(dst):
        os.remove(dst)
    # Windows can briefly hold a lock on a just-written file (antivirus
    # scan, indexing, etc.) even after the writer has closed it. Retry
    # a few times with a short backoff rather than failing the whole
    # export over a transient lock.
    last_exc = None
    for attempt in range(5):
        try:
            os.replace(src_path, dst)
            return dst
        except (PermissionError, OSError) as exc:
            last_exc = exc
            time.sleep(0.2 * (attempt + 1))
    raise last_exc


def _try_set(obj, method_name, *args):
    """Call obj.method_name(*args) if it exists on this KiCad version.

    Plot-option/writer setter names have drifted across KiCad 6/7/8/9
    releases. Rather than hard-failing the whole export over one
    renamed/removed setter, we skip it and keep going.
    """
    method = getattr(obj, method_name, None)
    if callable(method):
        try:
            method(*args)
        except Exception:
            pass


def _safe_step(fn, *args, **kwargs):
    """Run a non-essential export sub-step; swallow any failure so one
    optional file (e.g. a drill map on a KiCad version with a different
    API shape) can never take down the whole export.
    """
    try:
        return fn(*args, **kwargs)
    except Exception:
        return None


def export_gerbers(board, out_dir):
    """Plot the fab-required layer set to Gerber (RS-274X) files, named
    per the fab's fixed naming standard (see module docstring).

    Returns the list of file paths written.
    """
    os.makedirs(out_dir, exist_ok=True)
    layer_plan = _layer_plan(board)

    plot_controller = pcbnew.PLOT_CONTROLLER(board)
    plot_options = plot_controller.GetPlotOptions()

    # Core options — present on every KiCad 6+ version.
    plot_options.SetOutputDirectory(out_dir)
    plot_options.SetPlotFrameRef(False)
    plot_options.SetAutoScale(False)
    plot_options.SetScale(1)
    plot_options.SetMirror(False)
    plot_options.SetUseGerberAttributes(True)
    plot_options.SetUseAuxOrigin(True)
    plot_options.SetDrillMarksType(pcbnew.DRILL_MARKS_NO_DRILL_SHAPE)

    # Options whose names/availability vary by KiCad version — best effort.
    # Protel extensions stay off: we rename every output file ourselves
    # below to the fab's exact required name, so KiCad's own naming
    # scheme here is just a scratch name.
    _try_set(plot_options, "SetUseGerberProtelExtensions", False)
    _try_set(plot_options, "SetExcludeEdgeLayer", True)
    _try_set(plot_options, "SetSubtractMaskFromSilk", True)
    _try_set(plot_options, "SetDisableGerberMacros", False)

    # Plot every layer first, WITHOUT renaming yet. KiCad keeps a layer's
    # plot file open until the *next* OpenPlotfile() call or ClosePlot()
    # runs — renaming immediately after PlotLayer() (the previous version
    # of this function) raced that and failed with WinError 32 on Windows
    # ("used by another process"), because the file was still locked by
    # KiCad itself. Collect (generated_path, target_name) pairs during the
    # loop and only rename after ClosePlot() has released every handle.
    pending = []
    for layer_id, target_name in layer_plan:
        try:
            plot_controller.SetLayer(layer_id)
            plot_controller.OpenPlotfile(target_name, pcbnew.PLOT_FORMAT_GERBER, target_name)
            plot_controller.PlotLayer()
            pending.append((plot_controller.GetPlotFileName(), target_name))
        except Exception as exc:
            plot_controller.ClosePlot()
            raise RuntimeError(f"Failed to plot {target_name}: {exc}") from exc
    plot_controller.ClosePlot()

    written = []
    for generated_path, target_name in pending:
        written.append(_rename_to(generated_path, out_dir, target_name))

    return written


def export_drill(board, out_dir):
    """Write the fab's required drill set: DRILL.DRL (plated holes),
    NPTH.DRL (non-plated holes), SLOT.DRL (milled slots, best-effort
    split out of the PTH data), plus DRLMAP.GBR/DRLDRAW.GBR (a Gerber
    drill map/legend, duplicated under both names since the sample ships
    what looks like the same map content under each).

    Units/format: inches with explicit decimal points (no zero
    suppression), matching the sample's "X5.0039Y-4.0984"-style
    coordinates.

    Returns the path to DRILL.DRL (or out_dir if nothing was produced).
    """
    os.makedirs(out_dir, exist_ok=True)
    writer = pcbnew.EXCELLON_WRITER(board)
    aux_origin = board.GetDesignSettings().GetAuxOrigin()
    writer.SetOptions(
        False,           # mirror
        False,           # minimal header
        aux_origin,      # offset
        False,           # do NOT merge — fab wants separate PTH/NPTH files
    )

    zeros_fmt = getattr(pcbnew, "DECIMAL_FORMAT", 0)
    try:
        writer.SetFormat(False, zeros_fmt, 4, 4)  # metric=False (inches), 4 decimal digits
    except TypeError:
        try:
            writer.SetFormat(False)
        except Exception:
            writer.SetFormat(True)  # last resort: metric, still a valid drill file

    # Ask for a map file too if this KiCad version supports choosing the
    # format — we want it as Gerber to match DRLMAP.GBR/DRLDRAW.GBR.
    gerber_fmt = getattr(pcbnew, "PLOT_FORMAT_GERBER", None)
    if gerber_fmt is not None:
        _try_set(writer, "SetMapFileFormat", gerber_fmt)

    writer.CreateDrillandMapFilesSet(out_dir, True, True)

    # --- Sort generated files: PTH vs NPTH, and pick up the map file ---
    pth_path, npth_path = None, None
    for fname in os.listdir(out_dir):
        lower = fname.lower()
        if not lower.endswith(".drl"):
            continue
        full = os.path.join(out_dir, fname)
        if "npth" in lower:
            npth_path = full
        else:
            pth_path = full

    drill_target = os.path.join(out_dir, "DRILL.DRL")
    if pth_path:
        drill_target = _rename_to(pth_path, out_dir, "DRILL.DRL")

    if npth_path:
        _safe_step(_rename_to, npth_path, out_dir, "NPTH.DRL")

    # Drill map: KiCad may name it "<board>-drl_map.gbr" or similar —
    # find whatever Gerber-looking map file appeared that isn't one of
    # the layer Gerbers we already named, duplicate it under both
    # DRLMAP.GBR and DRLDRAW.GBR.
    _safe_step(_collect_drill_map, out_dir)

    # Best-effort slot split: pull any canned-slot (G85) records out of
    # DRILL.DRL into their own SLOT.DRL. If the pattern doesn't match
    # (route-mode slots, or a KiCad version that formats this
    # differently) this quietly does nothing and slots simply stay in
    # DRILL.DRL, which is still a completely valid drill file.
    if drill_target and os.path.isfile(drill_target):
        _safe_step(_split_slots, drill_target, out_dir)

    return drill_target if pth_path else out_dir


def _collect_drill_map(out_dir):
    known_names = {"top.gtl", "bottom.gbl", "topmask.gts", "bottommask.gbs",
                    "topsilk.gto", "bottomsilk.gbo", "toppaste.gtp",
                    "outline.gko", "drlmap.gbr", "drldraw.gbr"}
    for fname in os.listdir(out_dir):
        lower = fname.lower()
        if lower in known_names or not lower.endswith((".gbr", ".ger", ".gb1")):
            continue
        if "drl" in lower or "map" in lower or "drill" in lower:
            src = os.path.join(out_dir, fname)
            map_path = _rename_to(src, out_dir, "DRLMAP.GBR")
            shutil.copyfile(map_path, os.path.join(out_dir, "DRLDRAW.GBR"))
            return map_path
    return None


_SLOT_LINE_RE = re.compile(r"G85")


def _split_slots(drill_path, out_dir):
    """Heuristic split of canned-slot (G85) records out of an Excellon
    file into their own SLOT.DRL, matching the sample's per-purpose
    file layout. Leaves DRILL.DRL untouched if no slot records are found
    (i.e. this is a no-op safety net, never a required step).
    """
    with open(drill_path, "r", newline="") as f:
        lines = f.readlines()

    header_lines, tool_lines, body_lines = [], [], []
    in_header = True
    for line in lines:
        stripped = line.strip()
        if in_header:
            header_lines.append(line)
            if stripped == "%":
                in_header = False
            continue
        if stripped.startswith("T") and stripped[1:2].isdigit() and "X" not in stripped and "Y" not in stripped:
            tool_lines.append(line)
        else:
            body_lines.append(line)

    slot_lines = [l for l in body_lines if _SLOT_LINE_RE.search(l)]
    if not slot_lines:
        return None  # nothing to split out — leave DRILL.DRL as-is

    round_lines = [l for l in body_lines if not _SLOT_LINE_RE.search(l)]

    slot_path = os.path.join(out_dir, "SLOT.DRL")
    with open(slot_path, "w", newline="") as f:
        f.writelines(header_lines)
        f.writelines(tool_lines)
        f.writelines(slot_lines)
        if not slot_lines[-1].strip().startswith("M30"):
            f.write("M30\r\n")

    with open(drill_path, "w", newline="") as f:
        f.writelines(header_lines)
        f.writelines(tool_lines)
        f.writelines(round_lines)
        if not round_lines or not round_lines[-1].strip().startswith("M30"):
            f.write("M30\r\n")

    return slot_path
